Repository Donkstation/Donkstation, pull requests merged in 2021-11, with the labels that each got.

#60 Metastation: Added lights to much needed areas
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#61 Fixes type errors on Donk.dmm
  _maps/map_files/donk/Donk.dmm
Labels: mapping

#64 Adds an easter egg somewhere on MetaStation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#71 Fixed some broken exploration sprites
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/radio.dmi
Labels: sprites, size/XS

#73 Removal of "Yiff in Hell" crayon/spray
  code/game/objects/items/crayons.dm
  icons/effects/96x32.dmi
Labels: sprites, size/XS

#72 Modularization of donkstation changes
  beestation.dme
  code/modules/asset_cache/asset_list_items.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/power/smes.dm
  donkstation/DONKSTATION CONTRIBUTING.md
  donkstation/code/modules/job_tips/asset_list.dm
  donkstation/code/modules/job_tips/assets/borg.png
  donkstation/code/modules/job_tips/assets/captain.png
  donkstation/code/modules/job_tips/assets/ce.png
  donkstation/code/modules/job_tips/assets/cmo.png
  donkstation/code/modules/job_tips/assets/computer.png
  donkstation/code/modules/job_tips/assets/detective.png
  donkstation/code/modules/job_tips/assets/disabler.png
  donkstation/code/modules/job_tips/assets/disk.png
  donkstation/code/modules/job_tips/assets/fedora.png
  donkstation/code/modules/job_tips/assets/handcuffs.png
  donkstation/code/modules/job_tips/assets/hop.png
  donkstation/code/modules/job_tips/assets/hos.png
  donkstation/code/modules/job_tips/assets/ian.png
  donkstation/code/modules/job_tips/assets/id_gold.png
  donkstation/code/modules/job_tips/assets/lasergun.png
  donkstation/code/modules/job_tips/assets/radio.png
  donkstation/code/modules/job_tips/assets/rd.png
  donkstation/code/modules/job_tips/assets/revolver.png
  donkstation/code/modules/job_tips/assets/robo.png
  donkstation/code/modules/job_tips/assets/sec.png
  donkstation/code/modules/job_tips/assets/supermatter.png
  donkstation/code/modules/job_tips/assets/traitor.png
  donkstation/code/modules/job_tips/assets/warden.png
  donkstation/code/modules/job_tips/crewroles/captain.html
  donkstation/code/modules/job_tips/crewroles/chiefengineer.html
  donkstation/code/modules/job_tips/crewroles/chiefmedicalofficer.html
  donkstation/code/modules/job_tips/crewroles/detective.html
  donkstation/code/modules/job_tips/crewroles/headofpersonnel.html
  donkstation/code/modules/job_tips/crewroles/headofsecurity.html
  donkstation/code/modules/job_tips/crewroles/researchdirector.html
  donkstation/code/modules/job_tips/crewroles/securityofficer.html
  donkstation/code/modules/job_tips/crewroles/warden.html
  donkstation/code/modules/job_tips/job_tips.dm
  donkstation/code/modules/mob/simplemobs.dm
Labels: size/L

#69 Plasmaman envirosuits now spawn on all jobs
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
Labels: size/M

#74 A few Maid related changes
  beestation.dme
  code/modules/client/loadout/loadout_uniform.dm
  code/modules/vending/wardrobes.dm
Labels: size/S

#76 Minor Metastation medbay changes
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping, size/S

#65 Botany Changes/Reverts
  beestation.dme
  code/modules/hydroponics/biogenerator.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/research/designs/biogenerator_designs.dm
  code/modules/research/techweb/_techweb.dm
  donkstation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  donkstation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  donkstation/code/modules/research/techweb/_techweb.dm
Labels: size/L

#75 Trekkie outfits to the loadout shop
  beestation.dme
  code/modules/client/loadout/loadout_uniform.dm
  donkstation/code/modules/clothing/under/trek.dm
Labels: size/M

#78 Removes EOR sound
  sound/roundend/pogeurs_2.ogg
Labels: sound, size/XS

#77 Disabling Night Shift
  config/game_options.txt
Labels: Config Update, size/XS

#79 Adjusted blueshirt gear price/supply
  code/modules/vending/security.dm
Labels: size/XS
